language: php
php:
  - 5.4
  - 5.5

before_script:
  - wget http://pecl.php.net/get/yaml-1.1.0.tgz
  - tar -xzf yaml-1.1.0.tgz
  - sh -c "cd yaml-1.1.0 && phpize && ./configure && make && sudo make install"
  - echo "extension=yaml.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - sh -c "cd .."
  - psql -c "DROP DATABASE IF EXISTS strayFw_test;" -U postgres
  - psql -c "CREATE DATABASE strayFw_test;" -U postgres
  - sh -c "cp config/settings.tests.yml config/settings.yml"

script: phpunit --configuration .phpunit_pgsql.xml --coverage-text
